travis:
  secure:
    BINSTAR_TOKEN: az2bwRhxKcOzaPNI+UiLSjYhSRNX4PWyqHfzIfcYkHIaciRQsQzjucfKYpCtQJ82dSpZS3N66bevskNX2BoKOjUAuRE0DgocZiFRxyzHFG1TbW9DbIW9DKNGKH79JwjZmAN7saE605ALjfDoebE9XFW3BoBAGVgCCHt+nscD0TcUi3tPwnvyM97jjTb1jkZajy/nGFNnbgmg/H7aSA9WFjzt3QpHVjqcBBNDUU2jIgi6029WYrEmR5keKxWKNiS+lX4xlXjFJManSFKJxSakSHJh2+RC6Ul2IeVV9k5XjXym5iIGQ1OhdGFpTCrNOX/1bLu/HDXoUEd+OOCfpzKJOnRVXIJ4AK4/WDwwU66VjRkxcyK7jo4Qw2XUldvYFrTYrUkBT6IpUZKx+APKtOqsfPRpX+mTKW4+D084DdOvORYgbl1URhCT36cUSHBIpiZLExztX7VCEn/EzekvYj0JpCJcyZw13gUFrEW4ZGrhneXPOC0JWEQnOOVLEuCUzfszK2+5r13lRhaywg6tjqiHjP6XnEqzR6JMJm2LoSOIa2GF0ItT9ieHn9WitmdtZ2+brRa0V+x62nytlhUoS/6KX9IDG+Gri2nWa1A5gSlNMBAxPoeI3YoPL10iZsh1WDatobXu8ryVVFSZmfpbW1y9P647ExGtm5b2ueqPERqC0OM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
